name: Daily builds

on:
    schedule:
        -   cron: '30 14 * * *'

jobs:
    daily-builds:
        runs-on: ubuntu-latest
        name: Trigger
        steps:
            -   run: |
                  curl -H "Content-Type: application/json" \
                       --data '{"source_type": "Branch", "source_name": "master"}' \
                       -X POST ${{secrets.DOCKER_HUB_TRIGGER}}
